export const BID_RAISE_REQUEST = 'BID_RAISE_REQUEST';
export const BID_RAISE_SUCCESS = 'BID_RAISE_SUCCESS';
export const BID_RAISE_FAIL = 'BID_RAISE_FAIL';

export const BID_ACCEPT_REQUEST = 'BID_ACCEPT_REQUEST';
export const BID_ACCEPT_SUCCESS = 'BID_ACCEPT_SUCCESS';
export const BID_ACCEPT_FAIL = 'BID_ACCEPT_FAIL';

export const BIDS_LIST_REQUEST = 'BIDS_LIST_REQUEST';
export const BIDS_LIST_SUCCESS = 'BIDS_LIST_SUCCESS';
export const BIDS_LIST_FAIL = 'BIDS_LIST_FAIL';