export const RIDE_START_REQUEST = 'RIDE_START_REQUEST';
export const RIDE_START_SUCCESS = 'RIDE_START_SUCCESS';
export const RIDE_START_FAIL = 'RIDE_START_FAIL';

export const RIDE_END_REQUEST = 'RIDE_END_REQUEST';
export const RIDE_END_SUCCESS = 'RIDE_END_SUCCESS';
export const RIDE_END_FAIL = 'RIDE_END_FAIL';